### ISSUE TITLE
HH > RD_HiOrg: HH-RK 1368 (RTW)

### ISSUE THREAD

**Issue by JanSuerth** [mnai/LSS-Fahrzeuglisten#200]
**Bundesland**
HH 

**Liste/Datei**
RD_HiOrg

**Korrektur**
DRK Altona (Barmbek) - HH-RK 1368 - RTW (WAS Neufahrzeug)
Bereits als 81A gesehen.
https://bos-fahrzeuge.info/einsatzfahrzeuge/184714/Rotkreuz_Hamburg_RTW_HH-RK_1368

**Comment by mnai** [comment]
Mittlerweile seit 01.10. als 12R/S DRK RW Bahrenfeld im Einsatz.
