### ISSUE TITLE
SH > OD > FF GW-L2 FW Ahrensburg

### ISSUE THREAD

**Issue by KirschenHD11** [mnai/LSS-Fahrzeuglisten#274]
**Schleswig-Holstein**
Bitte einfügen

**Stormann**
Bitte einfügen

**FW Ahrensburg**
Bitte einfügen

**GW-A / GW-L2**
Bitte einfügen

**GW-A in 2022 durch GW-L2 ersetzt, neue Kennung Florian Stormarn 60/68-01 **
Bitte einfügen

**Comment by mnai** [comment]
Duplicated by #279
